/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOASYMCASSANDRA3
#define ROOASYMCASSANDRA3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAsymCassandra3 : public RooAbsPdf {
public:
  RooAsymCassandra3() {} ; 
  RooAsymCassandra3(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _tau_1,
	      RooAbsReal& _tau_2,
	      RooAbsReal& _tau_3,
	      RooAbsReal& _tau_4,
	      RooAbsReal& _tau_5,
	      RooAbsReal& _tau_6);
  RooAsymCassandra3(const RooAsymCassandra3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAsymCassandra3(*this,newname); }
  inline virtual ~RooAsymCassandra3() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy tau_1 ;
  RooRealProxy tau_2 ;
  RooRealProxy tau_3 ;
  RooRealProxy tau_4 ;
  RooRealProxy tau_5 ;
  RooRealProxy tau_6 ;
  
  Double_t evaluate() const ;

};
 
#endif
