/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCASSANDRA3
#define ROOCASSANDRA3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCassandra3 : public RooAbsPdf {
public:
  RooCassandra3() {} ; 
  RooCassandra3(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _tau_1,
	      RooAbsReal& _tau_2,
	      RooAbsReal& _tau_3);
  RooCassandra3(const RooCassandra3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCassandra3(*this,newname); }
  inline virtual ~RooCassandra3() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy tau_1 ;
  RooRealProxy tau_2 ;
  RooRealProxy tau_3 ;
  
  Double_t evaluate() const ;

};
 
#endif
