/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCASSANDRA
#define ROOCASSANDRA

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCassandra : public RooAbsPdf {
public:
  RooCassandra() {} ; 
  RooCassandra(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _tau_1,
	      RooAbsReal& _tau_2);
  RooCassandra(const RooCassandra& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCassandra(*this,newname); }
  inline virtual ~RooCassandra() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy tau_1 ;
  RooRealProxy tau_2 ;
  
  Double_t evaluate() const ;

};
 
#endif
