/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooIpatiaCommon.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include "TMath.h" 
#include "Math/SpecFunc.h"
#include "gsl/gsl_sf_bessel.h"

Double_t low_x_BK(Double_t nu,Double_t x){
  return TMath::Gamma(nu)*TMath::Power(2.,nu-1.)*TMath::Power(x,-nu);
}


Double_t low_x_LnBK(Double_t nu, Double_t x){
  return TMath::Log(TMath::Gamma(nu)) + (nu-1.)*log_de_2 - nu * TMath::Log(x);
}

Double_t BK(Double_t ni, Double_t x) {
  Double_t nu = TMath::Abs(ni);
  if ( x < 1e-06 && nu > 0) return low_x_BK(nu,x);
  if ( x < 1e-04 && nu > 0 && nu < 55) return low_x_BK(nu,x);
  if ( x < 0.1 && nu >= 55) return low_x_BK(nu,x);

  return gsl_sf_bessel_Knu(nu, x);
  //return ROOT::Math::cyl_bessel_k(nu, x);
}

Double_t LnBK(double ni, double x) {
  Double_t nu = TMath::Abs(ni);
  if ( x < 1e-06 && nu > 0) return low_x_LnBK(nu,x);
  if ( x < 1e-04 && nu > 0 && nu < 55) return low_x_LnBK(nu,x);
  if ( x < 0.1 && nu >= 55) return low_x_LnBK(nu,x);

  return gsl_sf_bessel_lnKnu(nu, x);
  //return TMath::Log(ROOT::Math::cyl_bessel_k(nu, x));
}




// Double_t eval(Double_t d, Double_t l, Double_t alpha, Double_t beta, Double_t delta, Double_t mu) {
//   Double_t sq2pi = sqrt(2*acos(-1));
//   Double_t cons1 = 1./sq2pi;
//   Double_t gamma = alpha;// sqrt(alpha*alpha-beta*beta);
//   Double_t dg = delta*gamma;
//   //Double_t mu_ = mu;// - delta*beta*BK(l+1,dg)/(gamma*BK(l,dg));
//   //Double_t d = x-mu;
//   Double_t thing = sqrt(delta*delta + d*d);
//   Double_t no = pow(gamma/delta,l)/BK(l,dg)*cons1;
//   Double_t num = no*BK(l-0.5,thing*alpha);
//   Double_t den = pow(thing/alpha,0.5-l);
//   Double_t cheat = exp(beta*d);//*(abs(beta) + 0.0001);
//  return  cheat*num/den ;
// }

Double_t LogEval(Double_t d, Double_t l, Double_t alpha, Double_t beta, Double_t delta) {
  //Double_t d = x-mu;
  //Double_t sq2pi = sqrt(2*acos(-1));
  Double_t gamma = alpha;//sqrt(alpha*alpha-beta*beta);
  Double_t dg = delta*gamma;
  Double_t thing = delta*delta + d*d;
  Double_t logno = l*TMath::Log(gamma/delta) - logsq2pi -LnBK(l, dg);
  /*printf("%e\n",exp(logno));
  printf("%e\n",LnBK(l-0.5,alpha*sqrt(thing)));
  printf("%e\n",(0.5-l)*(log(alpha)-0.5*log(thing)));
  printf("%e\n", logno + beta*d +(0.5-l)*(log(alpha)-0.5*log(thing)) + LnBK(l-0.5,alpha*sqrt(thing)));
  printf("%e\n", exp(logno + beta*d +(0.5-l)*(log(alpha)-0.5*log(thing)) + LnBK(l-0.5,alpha*sqrt(thing))));
  */
  return TMath::Exp(logno + beta*d +(0.5-l)*(TMath::Log(alpha)-0.5*TMath::Log(thing)) + LnBK(l-0.5,alpha*TMath::Sqrt(thing)));// + TMath::Log(TMath::Abs(beta)+0.0001) );

}

Double_t diff_eval(Double_t d, Double_t l, Double_t alpha, Double_t beta, Double_t delta){
  //Double_t sq2pi = sqrt(2*acos(-1));
  //Double_t cons1 = 1./sq2pi;
  Double_t gamma = alpha;// sqrt(alpha*alpha-beta*beta);
  Double_t dg = delta*gamma;
  //Double_t mu_ = mu;// - delta*beta*BK(l+1,dg)/(gamma*BK(l,dg));
  //Double_t d = x-mu;
  Double_t thing = delta*delta + d*d;
  Double_t sqthing = TMath::Sqrt(thing);
  Double_t alphasq = alpha*sqthing;
  Double_t no = TMath::Power(gamma/delta,l)/BK(l,dg)*sq2pi_inv;
  Double_t ns1 = 0.5-l;
  //Double_t cheat = exp(beta*d);//*(abs(beta) + 1e-04);
  //Double_t cheat = exp(beta*d);//*(abs(beta) + 0.0001);

  //no =  no*pow(alpha, ns1 )*pow(thing, 0.5*l - 5.0/4.0)*0.5*cheat;//exp(beta*d);

  //return no*(-alphasq*d* (BK(l - 3.0/2.0, alphasq) - BK(l + 0.5, alphasq)) + (2*beta*thing + 2*d*l - d)*BK(-ns1, alphasq));
  //return no*pow(alpha, -l + 1.0/2.0)*pow(thing, l/2 - 5.0/4.0)*(-d*alphasq*BK(l - 3.0/2.0, alphasq) - d*alphasq*BK(l + 1.0/2.0, alphasq) + 2*beta*thing*BK(l - 0.5, alphasq) + 2*d*l*BK(l - 0.5, alphasq) - d*BK(l - 0.5, alpha*sqthing))*exp(beta*d)/2;
  
  return no*TMath::Power(alpha, ns1)*TMath::Power(thing, l/2. - 1.25)*(-d*alphasq*(BK(l - 1.5, alphasq) + BK(l + 0.5, alphasq)) + (2.*(beta*thing + d*l) - d)*BK(ns1, alphasq))*TMath::Exp(beta*d)/2.;
}
 
